package com.acme.ecommerce.common.event;

public enum DomainEventType {
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_PUBLISHED,
    PRODUCT_UNPUBLISHED,
    INVENTORY_ADDED,
    INVENTORY_ADJUSTED,
    INVENTORY_RESERVED,
    INVENTORY_RELEASED,
    CART_COUPON_APPLIED,
    ORDER_CREATED,
    ORDER_CANCELLED
}
